            - имя: Настройка среды Node.js
  использует: actions/setup-node@v4.1.0
  с:
    # Установите always-auth в npmrc.
    always-auth: # необязательно, по умолчанию false
    # Версия Спецификация используемой версии. Примеры: 12.x, 10.15.1, >=10.15.0.
    node-version: # необязательно
    # Файл, содержащий версию Spec используемой версии. Примеры: package.json, .nvmrc, .node-version, .tool-versions.
    node-version-file: # необязательно
    # Целевая архитектура для использования Node. Примеры: x86, x64. Будет использовать системную архитектуру по умолчанию.
    архитектура: # необязательно
    # Установите этот параметр, если хотите, чтобы действие проверяло наличие последней доступной версии, удовлетворяющей спецификации версии.
    проверить-последнюю: # необязательно
    # Необязательный реестр для настройки аутентификации. Установит реестр в файле .npmrc и .yarnrc уровня проекта и настроит аутентификацию для чтения из env.NODE_AUTH_TOKEN.
    registry-url: # необязательно
    # Необязательная область для аутентификации по реестрам с областью действия. Будет возвращен владельцу репозитория при использовании реестра пакетов GitHub (https://npm.pkg.github.com/).
    область действия: # необязательно
    # Используется для извлечения распределений узлов из node-versions. Поскольку есть значение по умолчанию, оно обычно не предоставляется пользователем. При запуске этого действия на github.com достаточно значения по умолчанию. При запуске на GHES вы можете передать личный токен доступа для github.com, если вы сталкиваетесь с ограничением скорости.
    токен: # необязательно, по умолчанию ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # Используется для указания менеджера пакетов для кэширования в каталоге по умолчанию. Поддерживаемые значения: npm, yarn, pnpm.
    кэш: # необязательно
    # Используется для указания пути к файлу зависимости: package-lock.json, yarn.lock и т. д. Поддерживает подстановочные знаки или список имен файлов для кэширования нескольких зависимостей.
    cache-dependency-path: # необязательно
           
